[tox]
envlist = py310, py311, py312, py313, py314, py314t
isolated_build = True

[pytest]
testpaths = tests
addopts = --verbose

[testenv]
dependency_groups = test
commands = \
    pytest --basetemp={envtmpdir} {posargs}


[testenv:mypy]
dependency_groups = type_checking
skip_install=True
setenv = MYPY_CACHE_DIR = {temp_dir}/.mypy_cache
commands = mypy {posargs: src}

[testenv:flake8]
description = check the code style
dependency_groups = lint
skip_install=True
commands = flake8 {posargs: src}


[testenv:pylint]
description = check the code style
dependency_groups = lint
skip_install=True
commands =  pylint {posargs: src}


[testenv:pydocstyle]
skip_install = true
dependency_groups = lint
commands =
    pydocstyle {posargs: {toxinidir}/src}

[testenv:bandit]
skip_install = true
dependency_groups = lint

commands =
    bandit {posargs: --recursive {toxinidir}/src}
